# augprint
# Autogenerated from man page /usr/share/man/man1/augprint.1.gz
complete -c augprint -s v -l verbose -d 'Include the original numbered paths as comments in the output'
complete -c augprint -s p -l pretty -d 'Create more readable output by adding spaces and empty lines'
complete -c augprint -s r -o rN -l regexp -l regexp -d 'Generate regular expressions to match values, using a minumum length of N cha…'
complete -c augprint -s l -l lens -d 'Use \\s-1LENS\\s0 for the given file; without this option, augprint uses the de…'
complete -c augprint -s t -l target -d 'Generate the script for the \\s-1FILE\\s0 specified as if its path was really t…'

