# s3fs
# Autogenerated from man page /usr/share/man/man1/s3fs.1.gz
complete -c s3fs -s h -l help -d 'print help'
complete -c s3fs -l version -d 'print version'
complete -c s3fs -s f -d 'FUSE foreground option - do not run as daemon'
complete -c s3fs -s s -d 'FUSE single-threaded option (disables multi-threaded operation) '
complete -c s3fs -s o -d 'if it is not specified bucket name (and path) in command line, must specify t…'
complete -c s3fs -s u -l incomplete-mpu-list -d 'Lists multipart incomplete objects uploaded to the specified bucket'
complete -c s3fs -l incomplete-mpu-abort -d 'Delete the multipart incomplete object uploaded to the specified bucket'

