# vnstatd
# Autogenerated from man page /usr/share/man/man8/vnstatd.8.gz
complete -c vnstatd -l alwaysadd -d 'Enable automatic creation of new database entries for interfaces not currentl…'
complete -c vnstatd -l config -d 'Use  file as configuration file instead of using automatic configuration file…'
complete -c vnstatd -s d -l daemon -d 'Fork process to background and run as a daemon'
complete -c vnstatd -s D -l debug -d 'Provide additional output for debug purposes'
complete -c vnstatd -s g -l group -d 'Set daemon process group to  group during startup'
complete -c vnstatd -l initdb -d 'Create a new empty database without interface data and exit'
complete -c vnstatd -l noadd -d 'Disable the automatic creation of new database entries for all available inte…'
complete -c vnstatd -s n -l nodaemon -d 'Stay in foreground attached to the current terminal and start the update proc…'
complete -c vnstatd -s p -l pidfile -d 'Write the process id to  file and use it for locking so that another instance…'
complete -c vnstatd -s s -l sync -d 'Synchronize internal counters in the database with interface counters for all…'
complete -c vnstatd -s t -l timestamp -d 'Add a timestamp to the beginning of every print from the daemon when the proc…'
complete -c vnstatd -s u -l user -d 'Set daemon process user to  user during startup'
complete -c vnstatd -s v -l version -d 'Show current version of the daemon executable'
complete -c vnstatd -s '?' -l help -d 'Show a command option summary'

