[[scenefx-git]]
url = "https://github.com/wlrfx/scenefx.git"
commit = "2ec3505248e819191c37cb831197629f373326fb"

[[swaysettings-git]]
url = "https://github.com/ErikReider/SwaySettings"
commit = "8fb6210ad123654f3988cb8f3f59ab629bb0a747"
