# augparse
# Autogenerated from man page /usr/share/man/man1/augparse.1.gz
complete -c augparse -s I -l include -d 'Add \\s-1DIR\\s0 to the module loadpath.  Can be given multiple times'
complete -c augparse -s t -l trace -d 'Print a trace of the modules that are being loaded'
complete -c augparse -l nostdinc -d 'Do not search any of the default directories for modules'
complete -c augparse -l notypecheck -d 'Do not perform lens type checks'
complete -c augparse -l version -d 'Print version information and exit'

