# fingerprint-identifier
# Autogenerated from man page /usr/share/man/man1/fingerprint-identifier.1.gz
complete -c fingerprint-identifier -s d -l debug -d 'Send debugging information to syslog, using the auth facility'

