# greetd
# Autogenerated from man page /usr/share/man/man1/greetd.1.gz
complete -c greetd -s h -l help -d 'Show help message and quit'
complete -c greetd -s c -l config -d 'Specifies the configuration file to use'

