# hivexsh
# Autogenerated from man page /usr/share/man/man1/hivexsh.1.gz
complete -c hivexsh -s d -d 'Enable lots of debug messages'
complete -c hivexsh -s f -d 'Read commands from \\f(CW\\*(C`filename\\*(C\' instead of stdin'
complete -c hivexsh -s u -d 'Use heuristics to tolerate certain levels of corruption within hives'

