# imwheel
# Autogenerated from man page /usr/share/man/man1/imwheel.1.gz
complete -c imwheel -s 4 -l flip-buttons -d 'Flips the mouse buttons so that 4 is 5 and 5 is 4, reversing the Up and Down …'
complete -c imwheel -s b -l buttons -d 'Remap buttons in button-spec to interpreted wheel/thumb input'
complete -c imwheel -s c -l config -d 'Popup to configuration helper window imediately'
complete -c imwheel -s D -l debug -d 'Show all possible debug info while running'
complete -c imwheel -s d -l detach -d 'Actually this does the opposite of it\'s name, it prevents detachment from the…'
complete -c imwheel -s f -l focus -d 'Forces the X event subwindow to be used instead of the original hack that wou…'
complete -c imwheel -s g -l focus-events -d 'Disable the use of focus events for button grabs'
complete -c imwheel -s h -l help -d 'Short help on options plus version/author info'
complete -c imwheel -s k -l kill -d 'Attempts to kill old imwheel (useful only for --wheel-fifo method'
complete -c imwheel -s p -l pid -d 'Don\'t write a pid file for gpmwheel FIFO method'
complete -c imwheel -s q -l quit -d 'Quit imwheel before entering event loop'
complete -c imwheel -s s -l sensitivity -d '(Stick mice, Wheel FIFO method only)'
complete -c imwheel -s t -l threshhold -d 'Used with gpm only and then only with recognized stick mice'
complete -c imwheel -s W -l wheel-fifo -d 'Use the gpm/jamd wheel fifo instead of XGrabMouse'
complete -c imwheel -s X -l display -d 'Use XServer at a specified display in standard X form'
complete -c imwheel -s x -l transpose
complete -c imwheel -l ---- -l ----------- -l -------- -d 'Button1  (none)         Left Mouse Button Button2  (none)         Middle Mous…'

