# lollypop
# Autogenerated from man page /usr/share/man/man1/lollypop.1.gz
complete -c lollypop -s a -l play-ids -d 'Play ids'
complete -c lollypop -s d -l debug -d 'Debug Lollypop'
complete -c lollypop -s r -l set-rating -d 'Rate the current track'
complete -c lollypop -s t -l play-pause -d 'Toggle playback'
complete -c lollypop -s s -l stop -d 'Stop playback'
complete -c lollypop -s n -l next -d 'Go to next track'
complete -c lollypop -s p -l prev -d 'Go to prev track'
complete -c lollypop -s e -l emulate-phone -d 'Emulate a Librem phone'
complete -c lollypop -s v -l version -d 'Lollypop version'
complete -c lollypop -l display -d 'X-display to use AUTHOR Lollypop was written by CÃ©dric Bellegarde'

