# mysql-stress-test.pl
# Autogenerated from man page /usr/share/man/man1/mysql-stress-test.pl.1.gz
complete -c 'mysql-stress-test.pl' -l help
complete -c 'mysql-stress-test.pl' -l abort-on-error
complete -c 'mysql-stress-test.pl' -l check-tests-file
complete -c 'mysql-stress-test.pl' -l cleanup
complete -c 'mysql-stress-test.pl' -l log-error-details
complete -c 'mysql-stress-test.pl' -l loop-count
complete -c 'mysql-stress-test.pl' -l mysqltest
complete -c 'mysql-stress-test.pl' -l server-database
complete -c 'mysql-stress-test.pl' -l server-host
complete -c 'mysql-stress-test.pl' -l server-logs-dir
complete -c 'mysql-stress-test.pl' -l server-password
complete -c 'mysql-stress-test.pl' -l server-port
complete -c 'mysql-stress-test.pl' -l server-socket
complete -c 'mysql-stress-test.pl' -l server-user
complete -c 'mysql-stress-test.pl' -l sleep-time
complete -c 'mysql-stress-test.pl' -l stress-basedir
complete -c 'mysql-stress-test.pl' -l stress-datadir
complete -c 'mysql-stress-test.pl' -l stress-suite-basedir -d 'option.  oc o 2. 3'
complete -c 'mysql-stress-test.pl' -l stress-init-file
complete -c 'mysql-stress-test.pl' -l stress-mode
complete -c 'mysql-stress-test.pl' -l stress-tests-file -d 'option. ) oc o 2. 3'
complete -c 'mysql-stress-test.pl' -l suite
complete -c 'mysql-stress-test.pl' -l test-count
complete -c 'mysql-stress-test.pl' -l test-duration
complete -c 'mysql-stress-test.pl' -l threads
complete -c 'mysql-stress-test.pl' -l verbose

