# pam_fingerprint-gui
# Autogenerated from man page /usr/share/man/man8/pam_fingerprint-gui.8.gz
complete -c pam_fingerprint-gui -s d -l debug -d 'Send debugging information to syslog, using the auth facility'

