# wob
# Autogenerated from man page /usr/share/man/man1/wob.1.gz
complete -c wob -s c -l config -d 'Configuration file location'
complete -c wob -s v -l verbose -d 'Increase verbosity of messages, defaults to errors and warnings only'
complete -c wob -s V -l version -d 'Show the version number and quit'
complete -c wob -s h -l help -d 'Show help message and quit'

