# yarac
# Autogenerated from man page /usr/share/man/man1/yarac.1.gz
complete -c yarac -s d -d 'define external variable'
complete -c yarac -s w -l no-warnings -d 'Disable warnings'
complete -c yarac -l fail-on-warnings -d 'Treat warnings as errors.  Has no effect if used with  --no-warnings'
complete -c yarac -s v -l version -d 'Show version information'

