# Cyberpunk-Neon colours
draw_bold_text_with_bright_colors = true

[colors]

  [colors.primary]
  background = "0x000b1e"
  foreground = "0x0abdc6"

  # Normal colors
  [colors.normal]
  black = "0x123e7c"
  red = "0xff0000"
  green = "0xd300c4"
  yellow = "0xf57800"
  blue = "0x123e7c"
  magenta = "0x711c91"
  cyan = "0x0abdc6"
  white = "0xd7d7d5"

  # Bright colors
  [colors.bright]
  black = "0x1c61c2"
  red = "0xff0000"
  green = "0xd300c4"
  yellow = "0xf57800"
  blue = "0x00ff00"
  magenta = "0x711c91"
  cyan = "0x0abdc6"
  white = "0xd7d7d5"

  # Dim colors
  [colors.dim]
  black = "0x1c61c2"
  red = "0xff0000"
  green = "0xd300c4"
  yellow = "0xf57800"
  blue = "0x123e7c"
  magenta = "0x711c91"
  cyan = "0x0abdc6"
  white = "0xd7d7d5"

# Font
[font]
family = "Helvetica Neue"
style = "Bold"
size = 10.0

# Background
[background]
opacity = 0.0
background_opacity = 0.6

# Shell
# [shell]
# program = "/bin/fish"
# args = ["--login"]
